# Generated by Django 5.2.4 on 2025-07-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseincome',
            old_name='tax_amount',
            new_name='tax',
        ),
        migrations.AlterField(
            model_name='expenseincome',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
